models/pedido.py
from database import db, Column, Integer, String, Date, ForeignKey

class Pedido(db.Model):
    __tablename__ = "pedido"

    id = Column(Integer, primary_key=True, autoincrement=True)
    n_pedido = Column(String(4), nullable=False)
    data = Column(Date, nullable=False)
    usuario = Column(ForeignKey('usuario.id'), nullable=False)

    def __init__(self, n_pedido:str, data:Date, usuario:int):
        self.n_pedido = n_pedido
        self.data = data
        self.usuario = usuario

    @staticmethod
    def listar() -> list:
        lista_pedidos = Pedido.query.all()
        return lista_pedidos
    
    def editar(self, novo_n_pedido:str, nova_data:Date, novo_usuario:int):
        self.n_pedido = novo_n_pedido
        self.data = nova_data
        self.usuario = novo_usuario
        db.session.add(self)
        db.session.commit()
    
    def deletar(self):
        db.session.delete(self)
        db.session.commit()

models/pedido_has_produto.py
from database import db, Column, Integer, Numeric, ForeignKey

class PedidoHasProduto(db.Model):
    __tablename__ = "pedido_has_produto"

    pedido_id = Column(ForeignKey('pedido.id'))
    produto_id = Column(ForeignKey('produto.id'))
    qtd = Column(Integer, nullable=False)
    preco = Column(Numeric, nullable=False)

    def __init__(self, pedido_id:int, produto_id:int, qtd:int, preco:float):
        self.pedido_id = pedido_id
        self.produto_id = produto_id
        self.qtd = qtd
        self.preco = preco
    
    def cadastrar(self):
        db.session.add(self)
        db.session.commit()

    def editar(self, novo_produto_id:int, nova_qtd:int, novo_preco:float):
        self.produto_id = novo_produto_id
        self.qtd = nova_qtd
        self.preco = novo_preco
        db.session.add(self)
        db.session.commit()
    
    def deletar(self):
        db.session.delete(self)
        db.session.commit()

models/produto.py
from database import db, Column, Integer, String, Numeric

class Produto(db.Model):
    __tablename__ = "produto"

    id = Column(Integer, primary_key=True, autoincrement=True)
    nome = Column(String(45), nullable=False)
    preco = Column(Numeric, nullable=False)
    qtd_estoque = Column(Integer, nullable=False)

    def __init__(self, nome:str, preco:float, qtd_estoque:int):
        self.nome = nome
        self.preco = preco
        self.qtd_estoque = qtd_estoque
    
    def cadastrar(self):
        db.session.add(self)
        db.session.commit()
    
    @staticmethod
    def listar() -> list:
        lista_produtos = Produto.query.all()
        return lista_produtos

    def editar(self, novo_nome:str, novo_preco:float, novo_qtd_estoque:int):
        self.nome = novo_nome
        self.preco = novo_preco
        self.qtd_estoque = novo_qtd_estoque
        db.session.add(self)
        db.session.commit()
    
    def deletar(self):
        db.session.delete(self)
        db.session.commit()

models/usuario.py
from database import db, Column, Integer, String, Enum
from flask_login import UserMixin

class Usuario(db.Model, UserMixin):
    __tablename__ = "usuario"

    nome = Column(String(45), nullable=False)
    email = Column(String(45), primary_key=True)
    senha = Column(String(64), nullable=False)
    tipo_usuario = Column(Enum('cliente', 'funcionario', 'adm'), nullable=False)

    def __init__(self, nome:str, email:str, senha:str, tipo_usuario:str):
        self.nome = nome
        self.email = email
        self.senha = senha
        self.tipo_usuario = tipo_usuario
    
    def cadastrar(self):
        db.session.add(self)
        db.session.commit()
    
    @staticmethod
    def listar() -> list:
        lista_usuarios = Usuario.query.all()
        return lista_usuarios
    
    def editar(self, novo_nome:str, novo_email:str, nova_senha:str, novo_tipo_usuario:str):
        self.nome = novo_nome
        self.email = novo_email
        self.senha = nova_senha
        self.tipo_usuario = novo_tipo_usuario
        db.session.add(self)
        db.session.commit()
    
    def deletar(self):
        db.session.delete(self)
        db.session.commit()
    
    def get_id(self):
        return self.email

main.py
from flask import Flask, url_for
from secrets import token_hex
from flask_login import LoginManager
from flask_migrate import Migrate

#from routes.pedido import pedido_blueprint
#from routes.produto import produto_bluepinrt
from routes.usuario import usuario_blueprint

from database import db
from models.usuario import Usuario


login_manager = LoginManager()

app = Flask(__name__)
db.init_app(app)
login_manager.init_app(app)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///meubanco.db"
app.config["SECRET_KEY"] = token_hex()
migrate = Migrate(app, db)

#app.register_blueprint(pedido_blueprint, url_prefix="pedido")
#app.register_blueprint(produto_bluepinrt)
app.register_blueprint(usuario_blueprint)

@login_manager.user_loader
def carregar_usuario(id:int):
    return Usuario.query.get(id)

app.run("0.0.0.0", debug=True)

routes/pedido.py
from flask import Blueprint, request, render_template
from flask_login import login_required

from models.pedido import Pedido
from models.produto import Produto
from models.usuario import Usuario
from models.pedido_has_produto import PedidoHasProduto

pedido_blueprint = Blueprint("pedido", __name__)

@pedido_blueprint.route("/cadastrar")
@login_required
def cadastrar_pedido():
    cliente = request.form.get('id-cliente')
    data = request.form.get('data')

    for produto in request.form.get('produtos'):
        PedidoHasProduto()

routes/produto.py
from flask import Blueprint, request, render_template
from flask_login import login_required

from models.produto import Produto

produto_bluepinrt = Blueprint("produto", __name__)

@produto_bluepinrt
@login_required
def cadastrar_produto():
    nome = request.form.get('nome')
    preco = request.form.get('preco')
    qtd_estoque = request.form.get('qtd-estoque')
    
    produto = Produto(nome, preco, qtd_estoque).cadastar()
    return render_template("")

@produto_bluepinrt
@login_required
def listar_produtos():
    lista_produtos = Produto.listar()
    return render_template("", lista_produtos)

@produto_bluepinrt
@login_required
def editar_produto():
    id_produto = request.form.get('id-produto')
    novo_nome = request.form.get('novo-nome')
    novo_preco = request.form.get('novo-preco')
    novo_qtd_estoque = request.form.get('novo-qtd-estoque')

    produto = Produto.query.get(id_produto)
    produto.editar(novo_nome, novo_preco, novo_qtd_estoque)
    return render_template("")

@produto_bluepinrt
@login_required
def deletar_produto():
    id_produto = request.form.get('id-produto')
    produto = Produto.query.get(id_produto)
    produto.deletar()
    return render_template("")

routes/usuario.py
from flask import Blueprint, request, render_template
from flask_login import login_required, login_user, logout_user, current_user

from models.usuario import Usuario

usuario_blueprint = Blueprint('usuario', __name__)

@usuario_blueprint.route("/")
def index():
    return render_template("index.html")

@usuario_blueprint.route("/cadastrar", methods=["GET", "POST"])
def cadastrar_usuario():
    nome = request.form.get('nome')
    email = request.form.get('email')
    senha = request.form.get('senha')
    tipo_usuario = "cliente"

    usuario = Usuario(nome, email, senha, tipo_usuario)
    usuario.cadastrar()
    login_user(usuario)
    return render_template('painel.html', usuario=current_user)

@usuario_blueprint.route("/login", methods=["GET", "POST"])
def logar():
    usuario = Usuario.query.get(request.form.get('email'))
    login_user(usuario)
    return render_template('painel.html', usuario=current_user)

@usuario_blueprint.route("/logout")
def logout():
    logout_user()
    return render_template('index.html')

@usuario_blueprint.route("/deletar")
@login_required
def deletar_usuario():
    email_usuario = request.form.get("email")
    usuario = Usuario.query.get(email_usuario)
    usuario.deletar()
    return render_template("index.html")

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      src="https://kit.fontawesome.com/64d58efce2.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    <title>Snack | Login</title>
  </head>
  <body>
      <div class="container">
      <div class="forms-container">
        <div class="signin-signup">
          <form action="{{ url_for('usuario.logar') }}" method='POST' class="sign-in-form">
            <h2 class="title">Login</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="E-mail" name="email" required />
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Senha" name="senha" required/>
            </div>
            <input type="submit" value="Entrar" class="btn solid" />
            <a href="{{ url_for('static', filename='painel.html') }}">PAINEL TESTE</a>
            <p class="social-text">Entre em nossas redes sociais</p>
            <div class="social-media">
              <a href="#" class="social-icon">
                <i class="fab fa-instagram"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
              </a>
            </div>
          </form>
          <form action="{{ url_for('usuario.cadastrar_usuario') }}" method="POST" class="sign-up-form">
            <h2 class="title">Cadastrar</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="Username" name="nome" required/>
            </div>
            <div class="input-field">
              <i class="fas fa-envelope"></i>
              <input type="email" placeholder="Email" name="email" required/>
            </div>
            
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Senha" name="senha" required />
            </div>
            <input type="submit" class="btn" value="Cadastrar" />
          </form>
        </div>
      </div>

      <div class="panels-container">
        <div class="panel left-panel">
          <div class="content">
            <h3>Com fome?</h3>
            <p>
              Seja bem-vindo ao <b>Snack!</b>, cadastre-se aqui!
            </p>
            <button class="btn transparent" id="sign-up-btn">
              Cadastre-se
            </button>
          </div>
          <img src="{{ url_for('static', filename='login.svg') }}" class="image" alt="" />
        </div>
        <div class="panel right-panel">
          <div class="content">
            <h3>Já é um de nós?</h3>
            <p>
              Faça o seu login aqui, seja bem-vindo de volta!
            </p>
            <button class="btn transparent" id="sign-in-btn">
              Login
            </button>
          </div>
          <img src="{{ url_for('static', filename='cadastro.svg') }}" class="image" alt="" />
        </div>
      </div>
    </div>

    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>

templates/painel.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MVP</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='painel.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
</head>
<body id='body-pd'>
    <header class="header" id="header">
        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div> 
                <a href="#" class="nav_logo"> 
                <i><img src="{{ url_for('static', filename='logo.svg') }}" alt="..." height='60vh'></i> 
                <!-- <span class="nav_logo-name">MVP</span>  -->
                </a>
                <div class="nav_list"> 
                    <a href="#" class="nav_link active"> 
                        <i class='bx bx-grid-alt nav_icon'></i> 
                        <span class="nav_name">Home</span> 
                    </a> 
                    <a href="#" class="nav_link active"> 
                        <i class='bx bx-food-menu nav_icon'></i> 
                        <span class="nav_name">Produtos</span> 
                    </a> 
                    <a href="#" class="nav_link active"> 
                        <i class='bx bx-basket nav_icon'></i> 
                        <span class="nav_name">Meus Pedidos</span> 
                    </a> 
                    <hr style="color: white; margin: 1.5rem;">
                    <a href="#" class="nav_link active"> 
                        <i class='bx bx-user nav_icon'></i> 
                        <span class="nav_name">Usuários</span> 
                    </a> 
                    <a href="#" class="nav_link active"> 
                        <i class='bx bx-star nav_icon'></i> 
                        <span class="nav_name">Estoque</span> 
                    </a> 
            
                </div> 
                <a href="{{ url_for('usuario.logout') }}" class="nav_link log-out"> 
                    <i class='bx bx-log-out nav_icon'></i> 
                    <span class="nav_name">Sair</span> 
                </a>
        </nav>
    </div>
    <main>
        <section id="header-section">
            <h1>Olá, {{usuario.nome}}</h1>
            <button class="circle-carrinho">
                <i class='bx bx-basket nav_icon'></i>
            </button>
        </section>
        <section id="main-body">
            <h2>Cardápio de Hoje</h2>
                <div id="group-cards">
                    <div class="card" style="width: 18rem;">
                        <img src="https://anamariabraga.globo.com/wp-content/uploads/2017/12/coxinha-cremosa.jpg" class="card-img-top" alt="...">
                        <div class="card-body">
                        <h5 class="card-title" style="text-align: center; font-size: 2rem; font-weight: 700;">Coxinha</h5>
                        <p class="card-text" style="text-align: center; font-size: 1.5rem;">R$ 2,00</p>
                        <a href="#" class="btn btn-success" style="display: flex; justify-content: center; text-align: center;">Comprar</a>
                        </div>
                    </div>
                    <!--  -->
                    <div class="card" style="width: 18rem;">
                        <img src="https://anamariabraga.globo.com/wp-content/uploads/2017/12/coxinha-cremosa.jpg" class="card-img-top" alt="...">
                        <div class="card-body">
                        <h5 class="card-title" style="text-align: center; font-size: 2rem; font-weight: 700;">Coxinha</h5>
                        <p class="card-text" style="text-align: center; font-size: 1.5rem;">R$ 2,00</p>
                        <a href="#" class="btn btn-success" style="display: flex; justify-content: center; text-align: center;">Comprar</a>
                        </div>
                    </div>
                    <!--  -->
                    <div class="card" style="width: 18rem;">
                        <img src="https://anamariabraga.globo.com/wp-content/uploads/2017/12/coxinha-cremosa.jpg" class="card-img-top" alt="...">
                        <div class="card-body">
                        <h5 class="card-title" style="text-align: center; font-size: 2rem; font-weight: 700;">Coxinha</h5>
                        <p class="card-text" style="text-align: center; font-size: 1.5rem;">R$ 2,00</p>
                        <a href="#" class="btn btn-success" style="display: flex; justify-content: center; text-align: center;">Comprar</a>
                        </div>
                    </div>
                    <!--  -->
                    <div class="card" style="width: 18rem;">
                        <img src="https://anamariabraga.globo.com/wp-content/uploads/2017/12/coxinha-cremosa.jpg" class="card-img-top" alt="...">
                        <div class="card-body">
                        <h5 class="card-title" style="text-align: center; font-size: 2rem; font-weight: 700;">Coxinha</h5>
                        <p class="card-text" style="text-align: center; font-size: 1.5rem;">R$ 2,00</p>
                        <a href="#" class="btn btn-success" style="display: flex; justify-content: center; text-align: center;">Comprar</a>
                        </div>
                    </div>
                    <!--  -->
                </div>
            <!-- MAIS VENDIDOS -->
            <h2>Mais vendidos</h2>
            <div id="group-cards">
                <div class="card" style="width: 18rem;">
                    <img src="https://anamariabraga.globo.com/wp-content/uploads/2017/12/coxinha-cremosa.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title" style="text-align: center; font-size: 2rem; font-weight: 700;">Coxinha</h5>
                    <p class="card-text" style="text-align: center; font-size: 1.5rem;">R$ 2,00</p>
                    <a href="#" class="btn btn-success" style="display: flex; justify-content: center; text-align: center;">Comprar</a>
                    </div>
                </div>
                <!--  -->
                <div class="card" style="width: 18rem;">
                    <img src="https://anamariabraga.globo.com/wp-content/uploads/2017/12/coxinha-cremosa.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title" style="text-align: center; font-size: 2rem; font-weight: 700;">Coxinha</h5>
                    <p class="card-text" style="text-align: center; font-size: 1.5rem;">R$ 2,00</p>
                    <a href="#" class="btn btn-success" style="display: flex; justify-content: center; text-align: center;">Comprar</a>
                    </div>
                </div>
                <!--  -->
                <div class="card" style="width: 18rem;">
                    <img src="https://anamariabraga.globo.com/wp-content/uploads/2017/12/coxinha-cremosa.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title" style="text-align: center; font-size: 2rem; font-weight: 700;">Coxinha</h5>
                    <p class="card-text" style="text-align: center; font-size: 1.5rem;">R$ 2,00</p>
                    <a href="#" class="btn btn-success" style="display: flex; justify-content: center; text-align: center;">Comprar</a>
                    </div>
                </div>
                <!--  -->
                <div class="card" style="width: 18rem;">
                    <img src="https://anamariabraga.globo.com/wp-content/uploads/2017/12/coxinha-cremosa.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title" style="text-align: center; font-size: 2rem; font-weight: 700;">Coxinha</h5>
                    <p class="card-text" style="text-align: center; font-size: 1.5rem;">R$ 2,00</p>
                    <a href="#" class="btn btn-success" style="display: flex; justify-content: center; text-align: center;">Comprar</a>
                    </div>
                </div>
                <!--  -->
            </div>
        </section>





        <!-- MODAL -->
      
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='app.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>